---
apiVersion: v1
kind: Template
labels:
  template: agent-build-wendy-template
metadata:
  annotations:
    description: |-
      Jenkins service, with persistent storage.
      You must have persistent volumes available in your cluster to use this template.
    iconClass: icon-jenkins
    tags: jenkins
  name: agent-build-wendy
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${JENKINS_SERVICE_NAME}-${CONTEXT_DIR}
    annotations:
        slave-label: ${AGENT_LABEL}
    labels:
      role: jenkins-slave
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${JENKINS_SERVICE_NAME}-${CONTEXT_DIR}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${JENKINS_SERVICE_NAME}-${CONTEXT_DIR}:latest
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/${GITHUB_ORG}/wendy-jenkins-s2i-configuration
        ref: ${GITHUB_REF}
      contextDir: ${CONTEXT_DIR}
      type: Git
    strategy:
      dockerStrategy:
          noCache: true
          forcePull: true
      type: Docker
    triggers:
    - type: ImageChange
    - type: ConfigChange

parameters:
- description: The name of the github organization to reference in the configuration
  displayName: Github Organization
  name: GITHUB_ORG
  value: feedhenry
- description: The name of the repository branch to reference in the configuration
  displayName: Branch
  name: GITHUB_REF
  value: master
- description: The name of the OpenShift Service exposed for the Jenkins container.
  displayName: Jenkins Service Name
  name: JENKINS_SERVICE_NAME
  value: jenkins
- description: The label
  name: AGENT_LABEL
- description: The directory that houses the Dockerfile
  name: CONTEXT_DIR
